language: java
sudo: false
addons:
 sonarcloud:
   organization: "tomdatbenik"
script: 
  - cd IceWollowBackEndRework
  - mvn clean verify
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=tomdatbenik
