# Start with a base image containing Java runtime
FROM openjdk:11-jdk

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port available to the world outside this container
EXPOSE 8082

# The application's jar file
# The jar file's name is the pom.xml artifactId-version.jar, if this name needs to be changed, it needs to be changed a total of 3 times in this file
ARG JAR_FILE=target/WebSocketModule-2.2.2.RELEASE.jar

RUN mkdir /IceWollowBackEnd
WORKDIR /IceWollowBackEnd

# Add the application's jar to the container
ADD ${JAR_FILE} /IceWollowBackEnd/WebSocketModule-2.2.2.RELEASE.jar

# Run the jar file
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/IceWollowBackEnd/WebSocketModule-2.2.2.RELEASE.jar"]